rootProject.name = 'Live-Commerce'

include ':event-schema'
include ':common-lib'

include ':eureka'
include ':config'
include ':gateway'
include ':ai'
include ':chat'
include ':company'
include ':coupon'
include ':livebroadcast'
include ':notification'
include ':order'
include ':payment'
include ':product'
include ':user'