server:
  port: 19091

spring:
  webflux:
    static-path-pattern: /swagger-ui/**
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      forwarded-headers-strategy: framework
      discovery: # 서비스 디스커버리를 통해 동적으로 라우트를 생성항도록 설정
        locator:
          enabled: true
        default-filters:
          - PreserveHostHeader=true # 헤더 유지
          - AddRequestHeader=Authorization, {Authorization}
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /api/v2/auth/**, /v3/api-docs/user

        - id: company
          uri: lb://company
          predicates:
            - Path=/api/v1/companies/**, /v3/api-docs/company

        - id: coupon
          uri: lb://coupon
          predicates:
            - Path=/api/v1/coupon-policies/**, /api/v1/issued-coupons/**, /api/v2/issued-coupons/**, /api/v2/coupon-policies/**, /v3/api-docs/coupon

        - id: livebroadcast
          uri: lb://livebroadcast
          predicates:
            - Path=/api/v1/livebroadcasts/**, /v3/api-docs/livebroadcast

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**, /v3/api-docs/notification

        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**, /v3/api-docs/order, /api/v2/orders/**

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payments/**, /api/v2/payments/**, /api/v3/payments/**, /v3/api-docs/payment

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**, /api/v1/inventories/**, /v3/api-docs/product

        - id: chat
          uri: lb://chat
          predicates:
            - Path=/api/v1/chats/**, /v3/api-docs/chat

        - id: ai
          uri: lb://ai
          predicates:
            - Path=/api/v1/ai/**, /v3/api-docs/ai



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

  whitelist:
    paths:
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/v3/api-docs/**"

springdoc:
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: company
        url: /v3/api-docs/company
      - name: coupon
        url: /v3/api-docs/coupon
      - name: livebroadcast
        url: /v3/api-docs/livebroadcast
      - name: notification
        url: /v3/api-docs/notification
      - name: order
        url: /v3/api-docs/order
      - name: payment
        url: /v3/api-docs/payment
      - name: product
        url: /v3/api-docs/product
      - name: chat
        url: /v3/api-docs/chat
      - name: ai
        url: /v3/api-docs/ai